version: "3.9"

services: 
    front_builder:
        build: 
            context: ./frontend
        volumes:
            - /root/fronts/mess_front:/usr/front/build

    backend:
        build: ./backend
        container_name: backend
        restart: always
        command: gunicorn --bind 0.0.0.0:8000 --worker-class aiohttp.GunicornWebWorker --worker-connections=1000 --workers=1  main:app --reload
        environment:
          - PYTHONUNBUFFERED=1
        expose:
            - 8000

    nginx:
      build: ./nginx
      restart: always
      container_name: nginx
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./logs/nginx:/var/log/nginx
          - /root/fronts:/var/www
          # - ./certbot/conf:/etc/nginx/ssl
      ports:
          - 80:80
          - 443:443
      depends_on:
          - backend